repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: \.py$|\.pyi$
        language_version: python3.8
  - repo: local
    hooks:
      - id: prettier
        name: Prettier
        entry: ./frontend/node_modules/.bin/prettier --write --config ./frontend/.prettierrc
        files: ^frontend/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
      - id: typecheck
        name: Typecheck
        entry: yarn --cwd frontend tsc --noEmit
        files: \.js$|\.jsx$|\.ts$|\.tsx$
        language: node
        pass_filenames: false
      - id: eslint
        name: Eslint
        entry: ./frontend/node_modules/.bin/eslint --fix --ext .js --ext .jsx --ext .ts --ext .tsx --max-warnings 0 --config ./frontend/.eslintrc.js
        files: ^frontend/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
