repos:
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        files: \.py$|\.pyi$
        language_version: python3.8
  - repo: local
    hooks:
      # Script ./scripts/run_in_subdirectory.py was used to work around a
      # known problem with hooks in subdirectories when pass_filenames option
      # is set to true
      # See: https://github.com/pre-commit/pre-commit/issues/1417
      - id: prettier
        name: Prettier
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn prettier --write
        files: ^frontend/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
      - id: typecheck
        name: Typecheck
        entry: yarn --cwd frontend tsc --noEmit
        files: \.js$|\.jsx$|\.ts$|\.tsx$
        language: node
        pass_filenames: false
      - id: eslint
        name: Eslint
        entry: ./scripts/run_in_subdirectory.py frontend/ yarn eslint --fix --ext .js --ext .jsx --ext .ts --ext .tsx --max-warnings 0
        files: ^frontend/src/.*(.js|\.jsx|\.ts|\.tsx)$
        language: node
        pass_filenames: true
