name: CI Checks

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  python:
    uses: ./.github/workflows/python-versions.yml
    with:
      ref: ${{ github.ref_name }}

  javascript:
    uses: ./.github/workflows/js-tests.yml
    with:
      ref: ${{ github.ref_name }}

  cli-regression:
    uses: ./.github/workflows/cli-regression.yml
    with:
      ref: ${{ github.ref_name }}

  py-prod-deps-smoke:
    uses: ./.github/workflows/py-prod-deps-smoke-test.yml
    with:
      ref: ${{ github.ref_name }}

  cypress:
    uses: ./.github/workflows/cypress.yml
    with:
      ref: ${{ github.ref_name }}

  ci-check-summary:
    runs-on: ubuntu-latest

    # Consolidates results of above CI checks into a single pass/fail status check
    if: ${{ always() }}
    needs: [python, javascript, cli-regression, py-prod-deps-smoke, cypress]

    defaults:
      run:
        shell: bash -ileo pipefail {0}

    steps:
      - name: Overall CI Check Status
        if: ${{ needs.python.result == 'failure' || needs.javascript.result == 'failure' || needs.cli-regression.result == 'failure' || needs.py-prod-deps-smoke.result == 'failure' || needs.cypress.result == 'failure' }}
        run: exit 1
